### ISSUE TITLE
Open File

### ISSUE THREAD

**Issue by dannetzy** [quietust/nintendulator#7]
I want to open this file,but..... I don't know to open it

**Comment by quietust** [comment]
Could you be a bit more specific?

**Comment by spb1234** [comment]
When trying to open one of my ROMS I get the error ""Header is corrupted by "DiskDude!" - please repair it and try again"" however I don't know how to 1) repair the header, and 2) what it means by that.
EDIT: I am currently using v0.985
EDIT(again): I figured I'd try using the v0.980 stable release however I encounter the same error
EDIT: So to add more context, the ROM that I was trying to open was my Tetris ROM, however I figured I'd try with my LOZ ROM and it worked just fine. Therefore I think that it may be an issue with my Tetris ROM.

SOLVED: It must've been an issue with the ROM I had originally downloaded because I found another one and it works just fine.
